# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: android
jdk: oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.2
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository


script:
  - ./gradlew clean build -PdisablePreDex

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
